
name: CI Pipeline

on:
    push:
        branches: 
          - '*'
    pull_request:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest
        services:
          mysql:
            image: mysql:latest
            ports: 
              - 3306:3306
            env:
              DB_HOST: 127.0.0.1
              MYSQL_ROOT_PASSWORD: this is password
              MYSQL_DATABASE: uppdrag_hanterare_db
              MYSQL_USER: test_user
              MYSQL_PASSWORD: this is test password
              DB_PORT: 3306

              options: >-
                --health-cmd="mysqladmin ping"
                --health-interval=10s
                --health-timeout=5s
                --health-retries=3

        steps:
            - name: Check out code 
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                python-version: '3.12'

            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt
            
            - name: Set up test enviroment
              run: |

            - name: Run tests
              run: |
                pytest tests/
              env:
               
                DB_HOST: 127.0.0.1
                MYSQL_ROOT_PASSWORD: this is password
                MYSQL_DATABASE: uppdrag_hanterare_db
                MYSQL_USER: test_user
                MYSQL_PASSWORD: this is test password
                DB_PORT: 3306
                DATABASE_URL: mysql://test_user:this is test password@127.0.0.1:3306/uppdrag_hanterare_db

                